### ISSUE TITLE
Infinite Sign-in loop

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6658] opened 2022-05-06 17:29 UTC
I can't sign in to Replay. Every time I try it opens Chrome, looks like it successfully logs me in, and then lands back on the library screen without signing me in.

https://user-images.githubusercontent.com/5903784/167182544-6238e1ce-51f0-483f-9ba1-4fe66b26d543.mp4

@ryanjduffy assigning to you for now, but obviously feel free to redirect as appropriate!

**Comment by ryanjduffy** [comment] 2022-05-06 17:33
Then why'd you fix it?!?!? ;)

**Comment by jaril** [comment] 2022-05-12 14:46
Can't replicate for now. Might be a super super edge case?

@ryanjduffy I can keep an eye on it but also would like to close this unless it's actionable/we see another incident. Marking this off as a self-destructing issue if we don't hear any related activity in after a week.

**Comment by ryanjduffy** [comment] 2022-05-12 21:54
yup. :+1:

**Comment by jcmorrow** [comment] 2022-05-13 20:43
Sounds like we might have had this on a customer call @oliverdealb

**Comment by jaril** [comment] 2022-05-19 15:30
Iceboxing just because we don't have a clear idea on how to reproduce it and impact seems to be limited. Will keep an ear out in case we hear more stories about it, and can resurface it then.

**Comment by oliverdealb** [comment] 2022-05-27 22:43
Should we close this out then?

**Closed** 2022-05-27 23:55 UTC
Labels: icebox
