### ISSUE TITLE
Share recordings with a team

### ISSUE THREAD

**Issue by hbenl** [RecordReplay/devtools#3242] opened 2021-08-16 15:59 UTC
It should be possible to share recordings with a team instead of a single user.

**Comment by jasonLaster** [comment] 2021-08-16 16:19
Agreed. I think this is conceptually similar to https://github.com/RecordReplay/devtools/issues/2627

**Comment by jasonLaster** [comment] 2021-08-16 16:20
we can probably do them both at the same time

**Comment by jasonLaster** [comment] 2021-08-19 16:56
closing as a dupe of #2627

**Closed** 2021-08-19 16:56 UTC
Labels: feature-library
