### ISSUE TITLE
Missing pause line

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#3002] opened 2021-06-30 21:48 UTC
Sometimes when viewing a recording the pause line is missing

STR

1. visit https://replay.io/view?id=1dc1a6e8-23fb-4053-b05a-000d7f952da7
2. click on some of the comments
3. notice that the pause line does not always appear when clicking on a comment associated with script position

The recording below captures this behavior, LMK if you need access (I was logged into replay when recording it so left it private).

https://replay.io/view?id=77ed4cbc-2dd7-4bfa-97f5-87cda9fb47e2

**Comment by hbenl** [comment] 2021-07-01 08:35
Duplicate of #2927

**Closed by hbenl** 2021-07-01 08:35 UTC
