### ISSUE TITLE
Difficulty using player when parts of recording are unloaded

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#6622] opened 2022-05-01 23:10 UTC
When viewing a long replay and the entire thing isn't loaded, it's hard to use the video player to see what happened in the recording.

1. Playing through the recording stops at the end of the loaded region, even though all the graphics for the entire recording are available.
2. Clicking around on unloaded regions shows an "edit focus mode" dialog.  This dialog is unexpected and unnecessary unless the execution in this part of the recording needs to be examined, and I don't think clicking on unloaded areas should automatically bring it up.  If it comes up then I can't cancel out of it with escape or anything either, so the loaded regions have to change.
3. I don't really like the "We're having difficulties with your replay" copy in this dialog --- we're not having difficulty, it's just a long replay.

I think it should be possible to jump around the timeline in unloaded parts of the recording to see the video there, and to play through unloaded portions of the recording as well.

**Comment by jaril** [comment] 2022-05-12 15:30
Linking https://github.com/RecordReplay/devtools/issues/6622 here since it's somewhat related.

**Comment by jonbell-lot23** [comment] 2022-05-12 19:54
@jaril I think you linked this issue to itself

**Comment by jonbell-lot23** [comment] 2022-05-12 22:07
Here's where the design thinking is happening -> https://github.com/RecordReplay/design/issues/52

**Comment by jonbell-lot23** [comment] 2022-05-19 03:52
Update on this issue:

We've got a few different issues floating around that I'm reconciling against each other. I'll respond to each item above and provide some additional color:

1. Playing stops even though the video is available: tbd
2. Clicking on unloaded regions shows the "focus" dialog: I think this has been changed?
3. Difficulties dialog: this has also been changed: I think this has been changed?

I need some additional detail from the team to help me work through this.

When someone manually sets a focus window:
* We don't allow you to click anywhere else
* We don't show a dialog talking about difficulties
* Moving somewhere else requires manually adjusting your window

When the server unloads something on your behalf:
* I'm not sure what the current behaviour is here because it's hard for me to reproduce this state. Can anyone tell me if we're still doing items 2 and 3 from above?

**Comment by jasonLaster** [comment] 2022-05-19 14:14
It would be nice to discuss these interactions a bit more.

I dont know how we *could* do it, but ideally the video player would make it easy for users to know when they are at the bound of the window and could opt in to stopping or continuing. Not sure what audio/video editors do here, but there might be some lessons.

**Comment by jaril** [comment] 2022-05-19 15:38
To unblock the discussion and so @jonbell-lot23 has something to play with:

https://www.notion.so/replayio/202204200852-SendMessage-tips-13783b91a6194f058ff404269d307672

For example, in [this replay](https://app.replay.io/recording/replay-of-a-replay--8ccec6d3-9d89-40a4-b379-efd6337ee19f?point=14927853469561203019167625851699672&time=8654.604747774481&hasFrames=false), open the console and run `app.sendMessage("Session.unloadRegion", { region: { begin: 20000, end: 31227 } })`. That should get you into that state! 

Let me know if it'd be helpful to sync later today!

**Comment by jasonLaster** [comment] 2022-05-19 15:52
Thanks Jaril! quick loom
https://www.loom.com/share/fc0962c14a8c4811969a1237e9fdef11

**Comment by jonbell-lot23** [comment] 2022-05-19 18:14
Hey @jasonLaster @jaril @bvaughn  it's 6:13am for me but happy to meet about this later if we can find time.

Agree with the feedback here and on the other ticket. and the background is helpful. I think we can land something pretty quickly.

**Comment by jonbell-lot23** [comment] 2022-05-19 19:59
cc @jaril @jasonLaster @bvaughn I looked for time on the calendar but I don't see any good slots. So in the meantime, let's jump over here to this Discord file -> https://www.notion.so/replayio/Loading-buffering-loading-states-design-discussion-2c6b4e0a13f845ddb09221a3a3231631

**Comment by jcmorrow** [comment] 2022-05-19 21:23
> When the server unloads something on your behalf:

For clarification, there is no difference (AFAIK) between the client and the server doing the unloading from a UI perspective.

**Comment by jonbell-lot23** [comment] 2022-05-22 21:51
> For clarification, there is no difference (AFAIK) between the client and the server doing the unloading from a UI perspective.

Absolutely right. This is the beauty but also the agony of our design here. I think trying to explain four different lines and what they all mean would be a UX catastrophe ... but by making unloaded look the same in both cases, we have nuances to consider when messaging.

(For anyone reading this, and for historical reasons, I should point out that this was understand and very thoroughly considered 6+ months ago. None of these issues are surprising, we knew exactly what tradeoffs we were making and still believe they're better than the alternative.)

**Comment by jonbell-lot23** [comment] 2022-05-25 23:38
Hello team! For GitHub tracking reasons, I'm going to close this because it's being handled by @bvaughn over here: https://github.com/RecordReplay/devtools/issues/6913

This bug calls for three things, and all are being addressed in Global Loader 1.6:

* VIdeo should be playable anywhere on the timeline, even unloaded regions
* We shouldn't trigger the "edit focus mode" dialog when clicking an unloaded region
* We shouldn't message failure when we trigger "edit focus mode"

**Closed by jonbell-lot23** 2022-05-25 23:38 UTC
Labels: feature-timeline, ui polish, design-discussion
