### ISSUE TITLE
Replay intermittently crashes with white screen when loading a replay

### ISSUE THREAD

**Issue by ceceliacreates** [RecordReplay/devtools#6340] opened 2022-04-12 21:32 UTC
**Description:**
Wasn't able to reproduce in Replay, and after several refreshes it resolved, so this appears to be intermittent. Replay will start to load and then crash with a blank white screen.

**Steps to Reproduce:**
This is the replay I was opening when the issue occurred (public): https://app.replay.io/recording/react-calculator--58360b92-17ba-4847-9b90-bcc5ba0fb06b?point=21093705987865186607688438446555203&time=7350.703106567047&hasFrames=true#

Not sure if it's specific to a single replay.

**Expected Result:**

**Additional Context:**

* Log
[app.replay.io-1649798346625.log](https://github.com/RecordReplay/devtools/files/8476694/app.replay.io-1649798346625.log)

* Video (Kap):

https://user-images.githubusercontent.com/40367173/163057897-3cc31f0f-a0f4-4442-8c20-55804ef580c4.mp4

* Replay:

**Comment by markerikson** [comment] 2022-04-13 00:12
I've seen this a few times myself, but haven't specifically tried to repro it.

I may take a stab at this tomorrow.

**Comment by hbenl** [comment] 2022-04-13 08:54
Duplicate of #5384

**Closed by hbenl** 2022-04-13 08:54 UTC
