### ISSUE TITLE
Make test harness fail fast if session dies

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#2948] opened 2021-06-24 19:18 UTC
When looking at the test failures yesterday, I realize that since our DevTools tests are UI-focused, they try to do their steps and wait for stuff to happen like you'd expect, but if the session dies and we get the session-error modal, the tests will just sit there until they time out. 

It seems like ideally the `it`-block wrapper logic should detect the session modal and immediately consider the test failed at that point, thoughts?

**Comment by jcmorrow** [comment] 2021-11-12 21:08
@loganfsmyth I've done my best to make tests fail fast. There are still scenarios where they time out (but I think almost all of them were caused by the routing error fixed in #4473. I'm gonna close this for now!

**Closed by jcmorrow** 2021-11-12 21:08 UTC
Labels: Tooling

**Comment by loganfsmyth** [comment] 2021-11-12 21:52
Yay!
