### ISSUE TITLE
Should clicking and dragging on the timeline scrub through the recording

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#2116] opened 2021-03-15 21:56 UTC
I ran into #2115 while trying to do this :P

I wanted an easy way to skim through the video view, and currently the only way to do that is to play the video, or to hover over the timeline. The problem is that if you're looking at the video, it's hard to keep the mouse cursor properly centered on the timeline. 

If clicking and holding when your mouse is on the timeline kind of captured the cursor, then the timeline could just respond to horizontal motion in the cursor to to jump through the timeline and you wouldn't have to worry about vertical cursor placement.

**Comment by jonbell-lot23** [comment] 2021-03-15 22:01
I agree with this 100%. We used to have a very hover-centric UX and we're moving towards a more intentional one. I could see us going all-in on a dragger and a drag effect. To discuss.

**Comment by jasonLaster** [comment] 2021-04-05 16:32
closing as a dupe of #2236

**Closed by jasonLaster** 2021-04-05 16:32 UTC
