### ISSUE TITLE
React DevTools gets janky with its layout

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#6250] opened 2022-04-07 16:39 UTC
[Replay that Ben was working on when the bug happened](https://app.replay.io/recording/workflows-e2-dogfood--799a5573-0769-4aab-aa2f-86bee3ee781c?point=12980742148569603566669508410082222&time=9945&hasFrames=false)
```
BenWa — Yesterday at 3:47 PM
Also noticing that React DevTools doesn't sync with the frame perfectly all the time. Shows that my page is suspended when it's not. React DevTools also fails to highlight the node as a result: 
```
<img width="923" alt="image" src="https://user-images.githubusercontent.com/15959269/162253816-4788ca1d-ded0-447b-860f-e401d2a3c4b8.png">

**Comment by bvaughn** [comment] 2022-04-08 13:15
This looks like a React DevTools CSS bug. If the panel is wide enough for the error message, it looks okay:
![Screen Shot 2022-04-08 at 9 14 59 AM](https://user-images.githubusercontent.com/29597/162443115-199c69d7-e038-4672-84ea-3acd8a7d5044.png)
But when the panel is narrow, it looks bad:
![Screen Shot 2022-04-08 at 9 15 08 AM](https://user-images.githubusercontent.com/29597/162443117-1d0908dc-1319-442b-9f75-f6ff6f8c7aeb.png)

**Comment by bvaughn** [comment] 2022-04-08 13:35
I think this was actually fixed on the React DevTools side between version 4.17 (which is the version being loaded for the Replay in question) and the latest version (which we'll use for all Replays made with the newer browser release from this morning). Specifically I think this was fixed in https://github.com/facebook/react/pull/22483.

I tried to reproduce with React DevTools and it wraps ok:
![Screen Shot 2022-04-08 at 9 22 45 AM](https://user-images.githubusercontent.com/29597/162444853-3403f647-a14a-4ed5-a101-65ad05994c59.png)

I also looked at the underlying CSS in the Replay that Benoi reports:
![Screen Shot 2022-04-08 at 9 22 25 AM](https://user-images.githubusercontent.com/29597/162444893-3613545d-5f65-4b64-b307-e7c686baff9b.png)

And confirmed that it's significantly different than the CSS for a Replay made with the newer backend (and so one that loads the newer client):
![Screen Shot 2022-04-08 at 9 23 05 AM](https://user-images.githubusercontent.com/29597/162444894-7d33a594-a5d0-478a-8955-fd75fc548fbf.png)

I confirmed that the newer React DevTools UI properly handles this by forcing a newer Replay session (recorded with the newer browser) into erroring during inspect:
![Screen Shot 2022-04-08 at 9 33 00 AM](https://user-images.githubusercontent.com/29597/162446164-a27ecd4a-ce6f-497e-8754-721a874d35d7.png)

**Comment by bvaughn** [comment] 2022-04-08 13:35
Going to close this as "fixed" already.

**Closed by bvaughn** 2022-04-08 13:35 UTC
Labels: dish
