### ISSUE TITLE
[UX] Replays sluggish at first, with no indication why

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1863] opened 2021-02-19 04:23 UTC
I just recorded this Replay:
https://replay.io/view?id=25c48cbe-b7c1-4734-823b-2deb28fbfb96

It loads pretty quickly, but then I click the play button and it stalls out. I assume this is just because it's not done loading, but we need to make sure to message that so the page doesn't feel sluggish.

**Comment by jonbell-lot23** [comment] 2021-02-19 04:29
Here's a video showing my experience:

**Comment by jasonLaster** [comment] 2021-02-19 20:03
I think this is a duplicate of #1843. Could you provide suggestions there...

**Closed by jasonLaster** 2021-02-19 20:03 UTC
Labels: Perception
