### ISSUE TITLE
Print statement with three arrays renders strangely

### ISSUE THREAD

**Issue by jazzdan** [RecordReplay/devtools#5494] opened 2022-02-26 18:39 UTC
**Description:**
Here's a Replay of the problem https://app.replay.io/recording/printing-three-arrays-looks-weird--a0484c7b-f2a9-4a62-9b89-a04ad878400c

tl;dr printing three arrays renders in a weird pyramid structure

Here's the original replay https://app.replay.io/recording/more-ikneedata-investigation--2318c557-2c87-4090-8ad2-8b5952ba4e90

**Comment by abstractalgo** [comment] 2022-02-26 19:54
Not really a problem, just looks weird. The text and three items are each `inline-block` and they try to fit as much as possible in a single line, thus only text and one array element fit into the first line, then the next line can fit both remaining elements.

Unless we come with some heuristics how to render these somewhat special cases, not much we can do.

Here's an exact case in Chrome console, repro'd to a pyramid shape:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1355455/155857175-0731ec21-f78e-4622-a350-4e0eb4b5b69d.png">

<details>
<summary>code</summary>
<pre>
<code>
console.log("balblalblalba", [Array.from({length: Math.floor(Math.random()*20)+60}), Math.floor(Math.random()*80)], [Array.from({length: Math.floor(Math.random()*20)+60}), Math.floor(Math.random()*80)], [Array.from({length: Math.floor(Math.random()*20)+60}), Math.floor(Math.random()*80)])
</code>
</pre>
</details>

**Comment by jaril** [comment] 2022-03-02 15:13
Since it's not really unexpected behavior I'm closing this for now.

**Closed by jaril** 2022-03-02 15:13 UTC
