### ISSUE TITLE
"No Active Team" error shown when logging into Replay browser

### ISSUE THREAD

**Issue by ryanjduffy** [RecordReplay/devtools#5707] opened 2022-03-09 20:11 UTC
> I was getting some weirdness when trying to log into the Replay browser just now. I got an "unable to find active team" message. It logged me in via Google in Chrome then when switching back to Replay I got that message. I quit and restarted and it was fine, went right to my library. 

cc: @ceceliacreates

**Comment by ryanjduffy** [comment] 2022-03-09 20:16
I suspect there's still some race conditions happening here but it's not clear what exactly.

**Comment by jaril** [comment] 2022-03-23 14:09
@ryanjduffy do you think this will get done in March, or will it be sometime April?

**Comment by ryanjduffy** [comment] 2022-03-23 15:03
It needs to be fixed soon

**Comment by loganfsmyth** [comment] 2022-03-29 15:46
FYI I landed https://github.com/RecordReplay/backend/pull/5083 which may change how this manifests, I'd hope it will start saying that it's unauthenticated instead, and it's possible that will fix things, but since I don't actually know the cause of this bug, it may just change how it manifests. It hopefully won't show the "No active teams" part anymore at least.

**Comment by ryanjduffy** [comment] 2022-03-29 15:50
@loganfsmyth Thanks! I have a honeycomb trigger I'm monitoring for this so I'll let you know what happens

**Comment by loganfsmyth** [comment] 2022-03-30 17:40
That sounds very much like what I'd expect the behavior to be like for this now.

**Comment by ryanjduffy** [comment] 2022-03-30 18:50
@ceceliacreates - I don't _think_ that is the same bug because there isn't an auth prompt in this case:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/788456/160909202-a5898f74-f04d-49a5-a070-dde4a7f56bc8.png">

**Comment by ryanjduffy** [comment] 2022-03-30 18:50
@loganfsmyth - btw, I'm still seeing this error from honeycomb at least once a day so there's still something awry 🤷

**Comment by loganfsmyth** [comment] 2022-03-30 20:34
Which error specifically are you seeing in honeycomb? You'll get that error any time useGetNonPendingWorkspaces any time there is _any_ error with that query, so in this case I believe we're getting an UNAUTHENTICATED error from GraphQL because something about the auth flow is failing. I'd _guess_ it's still using the old expired token to make requests.

To my comment about what I expect to see, I guess I'd _hope_ that our internal token manager would recognize at some point that the token is still expired and redirect the user to the login flow again, instead of showing a random error about teams.

Due to the CORS error before, all GraphQL queries were throwing CORS errors and couldn't even see the response data for the GraphQL query, so now at least they should get a proper GraphQL response with an UNAUTHENTICATED error if the token is expired, so if something knows what that means and redirects to the login page for instance, that would explain the new behavior.

**Comment by ryanjduffy** [comment] 2022-03-30 21:27
I'm tracking DevtoolsUnexpectedError: https://ui.honeycomb.io/replay/datasets/backend/result/qiQaQBa5T3o/a/AY1YyyLt2p2

**Comment by ryanjduffy** [comment] 2022-04-01 20:05
Saw this in LogRocket today. I think the active team error is a red herring!

<img width="432" alt="image" src="https://user-images.githubusercontent.com/788456/161333925-6e68cf9d-5368-4bb2-a64b-eb1c752c0151.png">

https://app.logrocket.com/4sdo4i/replay/s/5-6594ce08-5820-472f-9055-e5629f6453f7/0?cursor=1648664903427&fromTab=sessions&t=1648658571635.136

**Closed** 2022-04-02 00:32 UTC
