### ISSUE TITLE
Screenshot is missing

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#3196] opened 2021-08-06 16:24 UTC
When I opened this replay the screenshot was missing:

<img width="1868" alt="Screen Shot 2021-08-06 at 9 21 50 AM" src="https://user-images.githubusercontent.com/254562/128541628-9f380557-b8d9-4d2c-857c-f75917297d99.png">

Here's a replay of it working, since i couldnt repro
https://app.replay.io/?id=58bf5102-6c3e-4281-ba5c-8128a1f2d6c6

**Comment by hbenl** [comment] 2021-09-06 14:43
Duplicate of #3378

**Closed by hbenl** 2021-09-06 14:43 UTC
Labels: Bug, feature-viewer
