### ISSUE TITLE
Loading screen shows while recording is uploading

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#1578] opened 2021-01-25 21:33 UTC
I just created a recording (aaffdb2b-796b-499c-b475-7fb6d2b5bb28) and the loading screen was showing even though the recording hadn't finished uploading.  We should be showing an uploading screen when the recording hasn't fully uploaded yet, as the uploading process can take a while and needs an actual progress notification.

**Comment by jasonLaster** [comment] 2021-01-25 23:52
closing as it is a dupe of #1554

**Closed by jasonLaster** 2021-01-25 23:52 UTC
