### ISSUE TITLE
[Debugger] multiple SOURCE tabs are created

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#292] opened 2020-07-31 16:04 UTC
https://webreplay.io/view?id=7ca73a45-b0af-4eb2-8e1d-48e90f660375

Every time I navigate to a generated source a new SOURCE tab is created. We should only have one and the name should probably be main.js

### Screenshot
<img width="1340" alt="Screen Shot 2020-07-31 at 9 02 00 AM" src="https://user-images.githubusercontent.com/254562/89053997-f0213d80-d30c-11ea-8345-cc4c1b5c3488.png">

### Console
it looks like the `source` does not have a url

<img width="1881" alt="Screen Shot 2020-07-31 at 9 12 37 AM" src="https://user-images.githubusercontent.com/254562/89054679-15627b80-d30e-11ea-8174-77f95b8ee453.png">

**Comment by hbenl** [comment] 2020-08-09 15:33
It seems that the relevant "source objects" in the recording are received from the server without a `url` property and that this bug has been fixed on the server side - that would explain why I couldn't reproduce the bug.

**Comment by jasonLaster** [comment] 2020-08-09 16:55
Agreed.

I just tried to repro with the initial project (https://replay.io/view?id=f05f2f58-b311-47f7-b48a-3104d72e80c9)


1. http://github.com/jasonlaster/web-replay-test
2. npm start

...

and could not repro

**Comment by hbenl** [comment] 2020-09-16 17:37
These scripts are sent by the server without a `url`, with `kind` set to `"other"`. I'm guessing these are `eval()`s.
So there is no filename to display, but there should be a unique name (like "SOURCE 3").
Furthermore there is a bug that opens new tabs for sources for which there already is a tab.
Both issues are fixed in #662.

**Closed** 2020-09-16 19:59 UTC
Labels: P1, Viewer
