### ISSUE TITLE
Dropdown is clipped

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#1848] opened 2021-02-17 15:49 UTC
**Description:**

![image](https://user-images.githubusercontent.com/254562/108229434-ac4d2480-70f4-11eb-8bb4-b26417d4064a.png)

**Comment by hbenl** [comment] 2021-02-17 15:56
This is also a duplicate of #1558

**Closed** 2021-02-17 15:56 UTC
