### ISSUE TITLE
It should be possible to toggle the video in devtools

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2738] opened 2021-05-31 00:36 UTC
Here's a proposal for this:
https://share.descript.com/view/vwosp86A9di

Here's a close-up of the toggle button:
![image](https://user-images.githubusercontent.com/9154902/120125421-d7bfcf00-c20c-11eb-989d-1ab8cee81c11.png)

**Comment by jaril** [comment] 2021-06-24 19:12
Duplicate of #2899.

**Closed by jaril** 2021-06-24 19:12 UTC
Labels: UI Polish
