### ISSUE TITLE
Can't resize the console

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1692] opened 2021-02-03 20:23 UTC
I can resize the console horizontally but not vertically.

Quick Descript showing the issue:
https://share.descript.com/view/MGwKOKVBW80

**Comment by jaril** [comment] 2021-02-03 20:28
Duplicate of #1692

**Closed by jaril** 2021-02-03 20:28 UTC

**Comment by jonbell-lot23** [comment] 2021-02-03 20:31
Oops I think you called this a dupe of this. Can you link to the dupe?
