### ISSUE TITLE
New comment are sometimes not focussed

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#5574] opened 2022-03-02 17:49 UTC
### Description

Some times when a comment is created, the editor is not focused, which leads to key strokes that do not update the editor

https://app.replay.io/recording/comment-did-not-focus--fb430269-cc65-4959-ad51-c837cdec4adf?point=92487787800941488227439655992170141&time=33660&hasFrames=false

**Comment by jaril** [comment] 2022-04-05 03:24
I just tested this and can't reproduce it anymore. Closing.

**Closed by jaril** 2022-04-05 03:24 UTC
Labels: Bug, feature-comments
