### ISSUE TITLE
Reporting `undefined` for variables that are definitely defined

### ISSUE THREAD

**Issue by jcmorrow** [RecordReplay/devtools#6512] opened 2022-04-21 18:39 UTC
https://app.replay.io/recording/replay--191fff91-a633-446f-8753-4e94054aa2cc

I am 99% sure that these `undefined` results are incorrect. If you evaluate `app.store.getState().app.loadedRegions`, which should be equivalent to what that selector is outputting, there is definitely data there, and obviously the timeline is loaded. Likewise with the requests table, there's a bunch of data in the table so `data` cannot be `undefined`. This is one of those places where we risk losing the user's trust completely because what we are confidently telling them is so clearly flat-out wrong.

**Comment by bvaughn** [comment] 2022-04-21 21:49
@jcmorrow Is this just the source mapping issue? Have you tried using `u` instead?

**Comment by hbenl** [comment] 2022-04-26 16:26
@jcmorrow could you add a comment in the recording where you're seeing the issue?

**Comment by jcmorrow** [comment] 2022-04-27 16:19
For a second I was thinking to myself "how the heck did I just make this issue without saying where the actual issue was?!" But then I realized that this is actually a replay of the issue, not the replay where I found it! Anyways, to reproduce, go to https://app.replay.io/recording/replay-network-request-details-not-loading--fa66a20b-1eb6-48ee-b9c7-3cb1c0b6c46e?point=63930155098606144678376594967888534&time=23290.399852364477&hasFrames=true and add a print statement to line 312 of `RequestDetails.tsx` and I used `loadedRegions` as my print statement, but also checked out other variables in that scope.

**Comment by jcmorrow** [comment] 2022-04-27 16:25
> @jcmorrow Is this just the source mapping issue? Have you tried using `u` instead?

I had not tried `u`, but I think you are right. I guess this is a question for you @hbenl... when our sourcemap tool "knows" the right answer, why wouldn't our print statements/pause evaluations also use that mapping?

Also - is there some way to detect when a source mapping is broken and tell the user "hey, this isn't working but it's because our source-map lookup isn't working, not because we think these variables are actually undefined"?

**Comment by hbenl** [comment] 2022-04-28 10:19
> when our sourcemap tool "knows" the right answer, why wouldn't our print statements/pause evaluations also use that mapping?

But it doesn't know the answer - if you look at the scopes panel, it shows only generated variable names.

> is there some way to detect when a source mapping is broken and tell the user "hey, this isn't working but it's because our source-map lookup isn't working, not because we think these variables are actually undefined"?

Yes, and usually we do this: when *some* variable names can't be mapped they're shown as "optimized away". When *all* variable names can't be mapped, the scopes panel shows the generated names with a warning that it couldn't map them to the original names.
But in this case the frames that we receive from the backend seem to indicate that there is no sourcemap, so no warning is shown.

**Comment by hbenl** [comment] 2022-04-28 10:19
Duplicate of #6255

**Closed by hbenl** 2022-04-28 10:19 UTC
Labels: Bug, feature-sourcemaps
