### ISSUE TITLE
"Save And Upload" modal interacts weirdly with "Socket closed due to an error" modal

### ISSUE THREAD

**Issue by loganfsmyth** [RecordReplay/devtools#2760] opened 2021-06-02 19:19 UTC
I created a new recording and got to "Save and Upload" and then I restarted my local backend, causing me to get the "Unexpected socket error" popup. When I clicked "Refresh" on the "Unexpected socket error" popup, the "Save and Upload"'s `onbeforeunload` handler returned `true` so the browser asked me to confirm if I wanted to leave. I pressed `Stay on Page` on that so I wouldn't refresh, and now the "Unexpected socket error" modal's button says "Refreshing..." forever and I can't press it again to try to navigate away, and that modal blocks my ability to press any buttons on "Save and Upload".

Should we prevent other modals from popping up if "Save and Upload" is active"? Seems like that would be enough to avoid this.

**Comment by jasonLaster** [comment] 2021-06-14 18:11
Yep. I think this is a dupe of https://github.com/RecordReplay/devtools/issues/2624

**Closed by jasonLaster** 2021-06-14 18:11 UTC
