### ISSUE TITLE
Icon gets wacky on page load

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#2261] opened 2021-04-05 22:37 UTC
Here's a Replay:
https://replay.io/view?id=6434b68c-1d97-4b95-b8bb-07ff56222e56&point=4867778306007430732824712474263655&time=2946&hasFrames=false

The overflow menu icon in the top right gets elongated when you first load the page.

**Comment by jasonLaster** [comment] 2021-04-05 22:49
duplicate of #2188

**Closed by jasonLaster** 2021-04-05 22:49 UTC
