### ISSUE TITLE
adding comment when not logged in causes error

### ISSUE THREAD

**Issue by karina-y** [RecordReplay/devtools#1461] opened 2021-01-04 23:16 UTC
**Description:**
i attempted to add a comment when i wasn't logged in and received an error in the console and the window to add my comment didn't show up. 

**Steps to Reproduce:**
1. log out or go incognito
2. navigate to any replay
3. try to add a comment via the timeline
4. notice the error in the console

**Screenshots:**
`Uncaught (in promise) Error: no such type exists in the schema: 'comments_insert_input'` in webpack:///./node_modules/@apollo/client/errors/index.js
![image](https://user-images.githubusercontent.com/19538307/103589137-9f0b0c00-4e9f-11eb-8620-1b5eabd19a3a.png)
![image](https://user-images.githubusercontent.com/19538307/103589157-a7fbdd80-4e9f-11eb-845e-2da397f5a352.png)

**Additional Context:**
something to consider: if we don't want users to add comments when they aren't logged in, we shouldn't show the icon to allow them to add any. i'm not sure if that's the root of this bug or not.

**Comment by jasonLaster** [comment] 2021-01-05 02:09
closing as a dupe of #1374

**Closed by jasonLaster** 2021-01-05 02:09 UTC
Labels: Bug, Comments, Timeline
