### ISSUE TITLE
Breakpoint returning 0 hits when I know there are 4

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1222] opened 2020-12-14 05:51 UTC
I was speaking with Jason earlier, and we thought this seemed like an issue on the backend.

STR:

1. Go to this Replay: https://replay.io/view?id=4b062335-3ec6-4210-adab-3fd601b0050f
2. Add a breakpoint to line 21, something we know was called 4 times
3. This is how it looks: 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/9154902/102045072-0acbfd00-3e3d-11eb-83fd-96f7448dee99.png">

Expected:
The breakpoint should say "4 hits" rather than "No hits."

Note: I have an interview at 11am PST/2pm EST on Monday. I'm hoping to have this resolved by then if possible.

Cheers!

**Comment by jonbell-lot23** [comment] 2020-12-14 17:51
Jaril and I have been looking into this, and we were able to get something working on another domain (glitch) ... but then it failed in a new way! Still investigating...

**Comment by jonbell-lot23** [comment] 2020-12-14 21:12
Latest insight from @loganfsmyth is that this is caused by the way we're using the submit button:

"The issue at the moment is that we're not handing it well because the submit button refreshes the page, so the recording actually has many copies of the main-5 file. If you add a e.preventDefault() to validateForm it'll make things a little more consistent for now I'd expect"

@jaril to file a broader bug around how we handle submit buttons when he gets a chance

**Comment by jasonLaster** [comment] 2020-12-21 21:14
closing this as we now know the issue is related to navigation and we're not planning on fixing this in the next month

**Closed by jasonLaster** 2020-12-21 21:14 UTC
