### ISSUE TITLE
stream search results

### ISSUE THREAD

**Issue by colbyr** [RecordReplay/devtools#4430] opened 2021-11-10 16:21 UTC
Context https://github.com/RecordReplay/backend/pull/3499#discussion_r745895297

The first backend search implementation sends all the results at once, but we set up the protocol in such a way that we can send results back incrementally.

**Comment by jasonLaster** [comment] 2021-11-22 04:16
closing as a duplicate of #3668

**Closed by jasonLaster** 2021-11-22 04:16 UTC
Labels: feature-debugger
