### ISSUE TITLE
Show indexing progress

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#2539] opened 2021-05-06 23:31 UTC
**Description:**

I'm often wondering when Replay will finish indexing and be able to show me breakpoint hits. Given this can be awhile, we should have some notion of global progress.

<img width="548" alt="Screen Shot 2021-05-06 at 4 30 00 PM" src="https://user-images.githubusercontent.com/254562/117377613-7e23e900-ae88-11eb-86bf-b5c0bf331a40.png">

**Comment by jonbell-lot23** [comment] 2021-05-20 08:22
Dupe of #2659

**Closed by jonbell-lot23** 2021-05-20 08:22 UTC
Labels: Performance, feature-debugger, needs-design
