### ISSUE TITLE
Node picker highlights nodes incorrectly

### ISSUE THREAD

**Issue by jaril** [RecordReplay/devtools#1060] opened 2020-11-23 20:18 UTC
I was looking at this [replay](https://replay.io/view?id=5199bf4b-a02a-423f-aea1-511b15233baf) and found that the node picker errantly highlights nodes when hovering on the DOM.

![image](https://user-images.githubusercontent.com/15959269/100011122-21bf8800-2d86-11eb-91c9-5b6799f8b3ff.png)

**Comment by jasonLaster** [comment] 2020-11-24 16:04
This might be a duplicate of #232

**Comment by hbenl** [comment] 2020-11-25 17:01
Closing as duplicate.

**Closed by hbenl** 2020-11-25 17:01 UTC
