### ISSUE TITLE
Breakpoint visual is breaking sometimes after Next migration

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#4384] opened 2021-11-08 20:54 UTC
Screenshot:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/9154902/140816533-023a1032-e92f-49ae-9475-310d400586c2.png">

Jason said he's seen this since the Next migration

**Comment by ryanjduffy** [comment] 2021-11-09 05:30
Would be great to capture a replay of this. I've poked around a bit but haven't been able to repro. If you can replay or hint at some repro step ideas, that'd be helpful!

**Comment by jonbell-lot23** [comment] 2021-11-09 08:42
Will keep you posted! It went away the next time it loaded, and I suspect that will happen again next time.

**Comment by jasonLaster** [comment] 2021-11-09 14:59
@ryanjduffy i bet this fixed it https://github.com/RecordReplay/devtools/issues/4357

it happens for me very rarely.... If i'm right this will go away, if i'm wrong a picture of the elements panel should help bisect the problem because some rules would not be matched...

**Comment by jasonLaster** [comment] 2021-11-09 15:31
<img width="1495" alt="Screen Shot 2021-11-09 at 7 30 20 AM" src="https://user-images.githubusercontent.com/254562/140953887-41970da7-8577-4082-b8db-edcca87c1536.png">

**Comment by ryanjduffy** [comment] 2021-11-09 20:54
Closing under the assumption this'll be resolved by ensuring our bundles are retried.

**Comment by ryanjduffy** [comment] 2021-11-09 21:05
Happened to catch this so I'm reopening. it's not a chunk loading error. the difference is the lack of an inline style `width` value on the codemirror gutter element a couple levels up from the selected node in the image above.

**Comment by ryanjduffy** [comment] 2021-11-09 22:09
The issue is that the breakpoint gutter isn't sized initially which breaks the width calc by code mirror. I'm not sure _why_ though so leaving this open for now.

**Comment by jonbell-lot23** [comment] 2021-11-09 23:43
Nice job spotting it!

**Comment by jonbell-lot23** [comment] 2021-11-17 19:12
Is this issue addressed @ryanjduffy ?

**Comment by jasonLaster** [comment] 2021-11-17 19:37
@jonbell-lot23 i think so

**Closed by jasonLaster** 2021-11-17 19:37 UTC
Labels: UI Polish
