### ISSUE TITLE
Comment's text input gets closed too eagerly

### ISSUE THREAD

**Issue by Andarist** [RecordReplay/devtools#5737] opened 2022-03-11 22:50 UTC
**Steps to Reproduce:**

1. start replying to a comment (type something in)
2. switch tab
3. get back to the tab with replay

**Expected Result:**

What I've already typed in the input should be preserved and the input should be visible. Most likely it's dismissed on blur or something but that makes UX suboptimal in a case like this.

**Comment by markerikson** [comment] 2022-03-12 06:27
Hah, I think this is a dupe of #5437 :)

**Comment by Andarist** [comment] 2022-03-12 06:35
I agree, I would only add to this that perhaps not only the text value should be persisted but the open state as well

**Closed** 2022-03-12 06:35 UTC

**Comment by jasonLaster** [comment] 2022-03-12 20:03
@abstractalgo will be working on improving commenting next week :)
