### ISSUE TITLE
Toolbar badging

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#4911] opened 2021-12-23 22:48 UTC
**Description:**

Today we use a solid fill to denote selected panes and paused. This can be confusing for users. 

* VS Code uses a left border to reinforce selected state. we use this pattern in other places too.
* We could badge pause state. This is one approach but there are others too. I don't love this partial icon because the grey bleeds. It'd probably be better to have something that overlays it or start with the left border and see if that is enough

https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=9774%3A123571

<img width="342" alt="Frame 298" src="https://user-images.githubusercontent.com/254562/147297436-7225188b-0def-493b-881f-c0f4e1f7d8fa.png">

---

### Two attempts at badging the pause icon

<img width="342" alt="Frame 299" src="https://user-images.githubusercontent.com/254562/147297437-81f4e52c-c951-45ef-a9b1-a0371eeda17d.png">
<img width="342" alt="Frame 300" src="https://user-images.githubusercontent.com/254562/147297594-97115aff-d8b1-4f77-a7e8-0aa04e448b85.png">

**Comment by jaril** [comment] 2021-12-30 16:48
I started thinking about the visual treatment here, but noticed that there's a bigger problem. When pause info panel leads to a useful debugging outcome, it usually goes in this order:

1) Pause on a line of code
2) Open pause info, then inspect either scopes and/or call stack
3) Get to an a-ha moment, and then finish/move on with your debugging

The problem is, it's _very_ possible for users to be stuck on step 1 because they're not on the pause info panel and it's not obvious that they should pop it open after navigating to a point. In such a case, they never even get a chance to get to a useful outcome because they don't even get to step 2.

We could pop it open by default whenever there's a navigate action to a pause point that corresponds with a line of code, but that feels like yanking the user around. This feels more like a place where we already have a subtle nudge — now we just need to make it an unmistakable nudge.

I'm trying to think of scenarios where the user is in a paused state but their pause info panel is not already open:

Scenario | Panel opened
--- | ---
The user opens a replay that has a code-related comment that we (intelligently) navigate to | Sources / Existing panel
The user opens a replay with query parameters that correspond with a pause point | Sources
The user navigate to a pause point via console message | Existing panel

In all of the above cases, the pause info panel will be in the paused visual state. I've also noticed that, even though the opened sidepanel will differ, the editor area will **always** open to the source file and show the paused line.

That means in the UI, after every navigation to a line of code, we already have reliably-open screen real estate that's sufficiently noisy that it will always grab the user's attention — the breakpoint widget.

### Idea
_Caveat: This is all under the assumption that the pause info is underutilized because the `pause on a line of code -> look at pause info` doesn't always happen even when necessary/helpful for the debugging session_

The breakpoint widget should act as a bridge towards the pause-info-related helpful debugging outcome.
- Mild version of this would be to indicate on the widget itself when one of its hits is currently paused on, and have some clickable _thing_ that would allow the user to learn more about that current paused point.
- Edgy version of this would be to throw the pause info (call stack, scopes) in with the widget. Make it collapsible so it doesn't take up too much space unless it needs to.

None of this is suggesting modifying/getting rid of the current pause info panel. If we intend to keep Replay's functionality as a vanilla step debugger, we need that part to work as it is currently.

**Comment by jasonLaster** [comment] 2022-01-08 20:28
Not realizing that they should go to the pause info panel feels like an education problem.

There are two ways we can help here
1. show a hat
2. open the panel by default the first time


I'm personally in favor of the hat since it is pretty explicit

<img width="342" alt="Frame 304 (1)" src="https://user-images.githubusercontent.com/254562/148658927-f9d84f20-3597-4d1d-988e-6760a03fe7ee.png">

**Closed** 2022-01-12 17:08 UTC
Labels: feature-toolbox
