### ISSUE TITLE
Can't delete or edit comments from sidebar

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#477] opened 2020-08-24 02:23 UTC
I just added a partial comment to a recording and can't figure out how to delete it or edit it to add the remaining contents.

**Comment by bhackett1024** [comment] 2020-08-24 02:24
Update: I can change comments by clicking their icon in the timeline, but it seems like this functionality should be available in the sidebar.

**Comment by jasonLaster** [comment] 2020-08-24 03:38
Yep - duplicate of #404

**Closed by jasonLaster** 2020-08-24 03:38 UTC
