### ISSUE TITLE
Paints not shown when viewing new recording

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/devtools#2785] opened 2021-06-07 13:29 UTC
See this loom video from @Andarist in discord:

https://www.loom.com/share/da5010eec37041e3a01f4c6d9eb9eba2

When initially playing the video (starting at 1:30 in the loom) the paints are never shown, and later on when jumping to a breakpoint (2:55 in the loom) the paint is also lost.  The recording itself is shown below.  Loading it now, replaying the video and jumping to the breakpoint as shown in the loom work totally fine.

https://replay.io/view?id=6d3dde62-b010-41d3-a51a-f4f37a17da7d

I suspect this is a frontend problem related to how the paints are being managed, especially with how we lose the paint when jumping to the breakpoint.  I've tried to reproduce this myself but things worked fine.  Having a recording of this problem would be really great to figure out what's going on.

**Comment by hbenl** [comment] 2021-06-07 14:31
@Andarist do you have the "Enable repainting" experiment turned on? That seems to have broken recently.

**Comment by hbenl** [comment] 2021-06-08 10:25
Fixed in #2787

**Closed by hbenl** 2021-06-08 10:25 UTC
Labels: Bug, Video

**Comment by Andarist** [comment] 2021-06-10 21:53
@hbenl yes - I had. I can confirm that the issue seems to be resolved - can't reproduce it anymore, regardless of this option being turned on or off. Thank you very much for a quick fix!
