### ISSUE TITLE
:bug: on DevTools: Breakpoints and print statements not d...

### ISSUE THREAD

**Issue by jperl** [RecordReplay/devtools#6048] opened 2022-03-29 20:15 UTC
:bug: on DevTools: Breakpoints and print statements not displaying
• Log in
• Go to replay
• Open breakpoint/ print statement pannel
• Add breakpoint
• Add print statement
Expected: Breakpoint and print statement to display in pannel
Result: Nothing is displayed
Effected tests:
• <https://www.qawolf.com/test/ckzzvdzeh86949250mg6157l2of|Add and delete breakpoint on user role> 
• <https://www.qawolf.com/test/ckzzwfwf880459950kvzpumjuxr?suite_id=cl1cjnibm10549750o3qbqc83gy|Assert user role not able to edit print statements>
<https://app.replay.io/recording/breakpoints-and-print-statements-no-displaying--0a774623-b096-454a-8bff-b0e00e7488b6|Replay of bug> \- [Ty](https://qawolfhq.slack.com/archives/C02GEJCC9JP/p1648584920746189)

**Comment by jaril** [comment] 2022-03-29 20:30
It was most likely caused by [this change](https://github.com/RecordReplay/devtools/commit/71085d3e3578fecc0e1a924872871e8aab561159).

Fixed by: https://github.com/RecordReplay/devtools/commit/379acc37abd2a97282a64026172d0c63e7dfc61c

**Closed** 2022-03-29 20:42 UTC
Labels: qa-wolf
