### ISSUE TITLE
[Replaying] replay.io

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/devtools#330] opened 2020-08-13 19:50 UTC
### Bug 1: inspector has many root nodes

STR:
1. go to https://replay.io/view?id=320d1de6-81df-4505-8e9c-44494b6c8cd0
2. open inspector 
3. refresh or expand notes

Couldn't repro while recording

---
### Bug 2: play in the timeline fails

STR:
1. go to https://replay.io/view?id=320d1de6-81df-4505-8e9c-44494b6c8cd0
2. press play in the timeline

Recording: https://replay.io/view?id=7315803c-54ac-47c8-aab1-16ce3280eaa3

Nothing happens

**Comment by bhackett1024** [comment] 2020-08-17 18:35
Bug 2 should be fixed now.  I tried a bit with 1. but I'm not able to reproduce it, can you try again to record the behavior?

**Closed** 2020-08-29 23:59 UTC
