### ISSUE TITLE
Events don't show in timeline until I turn on animation > request animation frame

### ISSUE THREAD

**Issue by jonbell-lot23** [RecordReplay/devtools#1194] opened 2020-12-10 02:02 UTC
This Descript explains what's happening:
https://share.descript.com/view/akSLNT4AgX2

Expected:
When I go to the console and turn on Control > Submit events, I expect to see them appear in the timeline

Actual:
Control > Submit doesn't seem to do anything. But Animation > Request Animation Frame does.

Here's a link to the Replay itself: https://replay.io/view?id=10d1a5ab-2e47-4576-bbaa-8cb0a5693390

**Comment by jasonLaster** [comment] 2020-12-10 21:22
hmm, i think what is happening under the hood is that we're not sending the requests for events until you select another new event.

It's weird because I'm not sure how to reproduce this bug. refreshing seems to work for me... 

Could you record this bug with Replay?

**Comment by jonbell-lot23** [comment] 2020-12-13 06:20
I haven't been able to reproduce this issue in a few days.

But I am seeing the events filter crash when I try to open it. For example, it happens here: https://replay.io/view?id=e0cbebde-8f15-4ed4-a495-2d1841ed0398

**Comment by jasonLaster** [comment] 2020-12-21 21:16
neither have i. lets close this and re-open if we see it

**Closed by jasonLaster** 2020-12-21 21:16 UTC
